export const QUESTION_BANK: string[] = [
  // Work & Office
  "Remote work vs. the return to office",
  "Should a four-day week become standard?",
  "Open offices kill deep work — agree?",
  "Should managers track employee productivity?",
  "Is hustle culture toxic or motivating?",
  "Should companies ban internal email?",
  "Is unlimited PTO a scam?",
  "Should salaries be public within companies?",
  "Is working from a coffee shop unprofessional?",
  "Should all meetings have a 30-minute hard cap?",
  "Is quiet quitting justified resistance?",
  "Should companies pay for home office setups?",
  "Are annual performance reviews useful?",
  "Is micromanagement ever justified?",
  "Should there be a maximum CEO-to-worker pay ratio?",
  "Is overworking a personal choice or systemic failure?",
  "Should employers allow paid moonlighting?",
  "Is workplace loyalty dead in 2025?",
  "Should offices have mandatory nap rooms?",
  "Are non-compete clauses ever ethical?",
  "Should employees own equity in the companies they build?",
  "Is Monday a structurally wasted workday?",
  "Should offices ban discussion of politics?",
  "Is a fun company culture a red flag?",
  "Should LinkedIn be shut down?",
  "Are team-building exercises a waste of money?",
  "Should countries mandate a minimum vacation amount?",
  "Is job-hopping smarter than staying loyal?",
  "Should companies subsidize employee fitness?",
  "Are reference checks an outdated hiring tool?",
  "Should dress codes still exist in 2025?",
  "Is the 9-to-5 schedule structurally obsolete?",
  "Should employees be free to run side businesses?",
  "Is remote work hurting young professionals' careers?",
  "Should companies monitor personal devices used for work?",
  "Is office politics inevitable in every org?",
  "Should workers have seats on corporate boards?",
  "Is automation a threat or opportunity for workers?",
  "Should internships always be paid?",
  "Are open-plan offices a failed experiment?",
  "Should it be harder for companies to fire employees?",
  "Is the gig economy fundamentally exploitative?",
  "Should bonuses replace salary increases?",
  "Does mandatory diversity training actually work?",
  "Should companies share profits with all staff?",
  "Is culture more important than compensation?",
  "Should every engineer manager still write code?",
  "Is imposter syndrome a feature or a bug?",
  "Are daily stand-up meetings net useful?",
  "Should there be a global minimum wage?",
  "Is the handshake still a useful business ritual?",
  "Should employers pay for employee therapy?",
  "Is hybrid work the worst of both worlds?",
  "Should there be a right to disconnect from work?",
  "Is the annual bonus model broken?",
  "Should companies be penalized for burnout?",

  // Education
  "Is college worth the debt in 2025?",
  "Should homework be abolished for under-16s?",
  "Are standardized tests a fair measure of ability?",
  "Should smartphones be banned in all classrooms?",
  "Is university a scam for most career paths?",
  "Should trade schools be promoted equally to college?",
  "Is grade inflation ruining higher education?",
  "Should school start at 9am or later?",
  "Is online learning as effective as in-person?",
  "Should teachers be paid more than most executives?",
  "Is the Montessori method superior?",
  "Should coding be mandatory from primary school?",
  "Is taking a gap year a smart investment?",
  "Should private schools be abolished?",
  "Is blanket student loan forgiveness fair?",
  "Should financial literacy be taught from age 10?",
  "Are MBAs still worth the cost?",
  "Should attendance be mandatory in university?",
  "Is the letter grading system outdated?",
  "Should religious instruction be allowed in public schools?",
  "Is academic tenure harming universities?",
  "Should free speech be unlimited on campuses?",
  "Is physical education class a waste of curriculum time?",
  "Should students have formal power to grade their teachers?",
  "Are gifted programmes structurally elitist?",
  "Is arts education chronically undervalued?",
  "Should school uniforms be mandatory globally?",
  "Is early childhood education underfunded everywhere?",
  "Should university be free for all citizens?",
  "Are PhD programmes exploiting graduate students?",
  "Should physical libraries be replaced by digital access?",
  "Is rote memorization a useful skill in the AI era?",
  "Should cursive writing still be taught?",
  "Is the traditional lecture-room model dead?",
  "Should students design their own learning curriculum?",
  "Should social media literacy be a core school subject?",
  "Should history education prioritize local or global events?",
  "Are school rankings doing more harm than good?",
  "Should exams be open-book and open-internet?",
  "Is academic fraud increasing and who is responsible?",
  "Should competitive sport be compulsory in school?",
  "Are summer breaks too long for modern economies?",
  "Should all children learn a second language before age 8?",
  "Is the education system structurally biased against boys?",
  "Should socioeconomic background be factored into college admissions?",
  "Are study groups more effective than solo study?",
  "Is private tutoring an unfair advantage?",
  "Should schools teach meditation and mindfulness?",
  "Is a high dropout rate always a school failure?",
  "Should teachers have more authority than parents over learning?",
  "Is standardized curriculum stifling creativity?",
  "Should students be allowed to use AI in exams?",
  "Is the school calendar designed for industrial not modern society?",
  "Should every student learn basic programming logic?",

  // AI & Technology
  "Will AI replace most white-collar jobs in 10 years?",
  "Should AI-generated content be permanently labelled?",
  "Is AI making humans less creative overall?",
  "Should companies disclose when AI shortlists job candidates?",
  "Should algorithm-driven feeds be banned?",
  "Is Big Tech too powerful to regulate?",
  "Should facial recognition be banned in public spaces?",
  "Is the metaverse a permanently failed experiment?",
  "Should smartphones ship with enforced daily limits?",
  "Is surveillance capitalism an ethical business model?",
  "Should AI systems ever have legal personhood?",
  "Is personal data privacy effectively dead?",
  "Should tech companies pay citizens a data dividend?",
  "Is screen time the new second-hand smoking?",
  "Should autonomous weapons be internationally banned?",
  "Is open-source AI more dangerous than closed AI?",
  "Should AI-generated art be allowed in competitions?",
  "Are recommendation algorithms radicalizing people?",
  "Should there be a universal right to be forgotten online?",
  "Is quantum computing an existential cybersecurity threat?",
  "Should children under 13 be allowed on any social platform?",
  "Is the attention economy fundamentally unethical?",
  "Should self-driving cars be permitted on public roads now?",
  "Is digital addiction a recognized medical condition?",
  "Should AI be allowed to make binding legal decisions?",
  "Should tech monopolies be forcibly broken up?",
  "Is automation accelerating wealth inequality?",
  "Should robots and AI systems pay a form of tax?",
  "Is artificial general intelligence achievable?",
  "Should AI be used in criminal sentencing?",
  "Is internet access a fundamental human right?",
  "Should deepfakes be criminalized globally?",
  "Is Silicon Valley a net positive for human society?",
  "Should gene editing of human embryos be allowed?",
  "Is blockchain technology fundamentally overrated?",
  "Should AI chatbots replace human therapists?",
  "Is social media the primary driver of teen anxiety?",
  "Should governments ban end-to-end encryption?",
  "Is coding the new essential literacy?",
  "Should AI diagnose diseases before human doctors?",
  "Is tech optimism dangerously naive?",
  "Should UBI replace welfare due to automation?",
  "Should tech CEOs be personally liable for platform harms?",
  "Is cloud dependency making society fragile?",
  "Should there be a binding global AI treaty?",
  "Are tech monopolies structurally inevitable?",
  "Is the digital divide the defining inequality of our era?",
  "Should AI be required to identify itself in conversations?",
  "Is social media doing more harm than the printing press did?",
  "Should there be a pause on frontier AI development?",
  "Is TikTok a legitimate national security threat?",
  "Should data centers be powered exclusively by renewables?",
  "Is the attention economy compatible with democracy?",

  // Kids & Parenting
  "Should social media require proof of age 16+?",
  "Is helicopter parenting creating anxious adults?",
  "Should children get smartphones before 13?",
  "Are video games net good for child development?",
  "Should children be required to do household chores?",
  "Is homeschooling better than traditional schooling?",
  "Should children receive a weekly allowance?",
  "Are participation trophies psychologically harmful?",
  "Should children be allowed to choose their own religion?",
  "Is free-range parenting irresponsible or healthy?",
  "Should screen time be strictly limited by law?",
  "Are boarding schools beneficial for children?",
  "Should parents read their teenager's messages?",
  "Is competitive sport putting too much pressure on children?",
  "Should children have a formal vote in family decisions?",
  "Are demanding parents producing more successful children?",
  "Should children learn coding before handwriting?",
  "Is full-time daycare before age 3 harmful to development?",
  "Should parents be held legally responsible for their children's crimes?",
  "Are child-free adults unfairly judged by society?",
  "Is physical discipline ever justifiable?",
  "Is it wrong to raise children without any religion?",
  "Should children be raised vegetarian by default?",
  "Do toy guns normalize violence in children?",
  "Should children learn to invest money by age 10?",
  "Is social media destroying the concept of childhood?",
  "Should children be allowed to quit sports midseason?",
  "Is there a link between helicopter parenting and adult anxiety?",
  "Should parents discuss death with children honestly and early?",
  "Is lying to children about Santa Claus harmful?",
  "Should parents be prevented from posting children's photos online?",
  "Are two-parent households definitively better for children?",
  "Should children be exposed to failure intentionally?",
  "Is co-sleeping with infants dangerous or beneficial?",
  "Should children address adults by first names?",
  "Are gifted and talented programmes creating unhealthy pressure?",
  "Should teenagers have a legally enforced curfew?",
  "Is raising gender-neutral children beneficial or harmful?",
  "Should becoming a parent require a licence?",
  "Are only children at a developmental disadvantage?",
  "Should the voting age be lowered to 16?",
  "Is digital peer pressure worse than physical peer pressure?",
  "Should children have a legal voice in custody proceedings?",
  "Is baby monitor culture excessive parental anxiety?",
  "Should parents complete college applications for their children?",
  "Is youth competitive sport starting too early?",
  "Should parents take phones away as punishment?",
  "Are parents too obsessed with Ivy League admissions?",
  "Should teenagers have complete privacy from parents?",
  "Is disciplining a child in public acceptable?",

  // Society & Politics
  "Should voting be mandatory for all eligible citizens?",
  "Is cancel culture causing more harm than good?",
  "Should billionaires be allowed to exist?",
  "Is social media making political discourse more extreme?",
  "Should the voting age be lowered to 16?",
  "Is meritocracy a useful myth or a reality?",
  "Should all recreational drugs be decriminalised?",
  "Is free speech an absolute right?",
  "Should prison aim primarily to rehabilitate or punish?",
  "Is patriotism a healthy or a dangerous feeling?",
  "Should assisted dying be universally legal?",
  "Is affirmative action a fair or counterproductive policy?",
  "Should supreme court judges have term limits?",
  "Is liberal democracy in global decline?",
  "Should universal healthcare be a constitutional right?",
  "Is political lobbying legalised corruption?",
  "Should the death penalty be abolished globally?",
  "Is immigration a net economic positive for host countries?",
  "Should sex work be fully decriminalized?",
  "Is nationalism inherently dangerous?",
  "Should public figures surrender most of their privacy?",
  "Is civil disobedience ever morally justified?",
  "Should all drugs be taxed and regulated like alcohol?",
  "Is a Universal Basic Income financially feasible?",
  "Should national service be mandatory for all citizens?",
  "Is global governance an inevitable next step?",
  "Should all national borders be open?",
  "Is political correctness stifling open debate?",
  "Should public media be state-funded?",
  "Is capitalism the best economic system available?",
  "Should all democracies adopt ranked-choice voting?",
  "Is the two-party political system broken?",
  "Should the electoral college be abolished?",
  "Is street art vandalism or legitimate culture?",
  "Should religious institutions pay taxes?",
  "Is aggressive wealth redistribution ethical?",
  "Should elections be conducted entirely digitally?",
  "Is the United Nations effective?",
  "Should reparations be paid for historical injustices?",
  "Is productive civil discourse still possible?",
  "Should protests that block traffic be illegal?",
  "Is mainstream media too biased to be trusted?",
  "Should elected officials be subject to minimum competency tests?",
  "Is anarchism a viable political philosophy?",
  "Should corporations have the same political rights as citizens?",
  "Is the right to bear arms outdated in modern society?",
  "Should there be a maximum income cap?",
  "Is global inequality a solvable problem?",
  "Should military spending be capped by international treaty?",
  "Is revolution ever morally justified?",
  "Should gerrymandering be a criminal offense?",
  "Is the welfare state creating dependency?",
  "Should every country adopt a written constitution?",

  // Health & Wellness
  "Should junk food be taxed at higher rates?",
  "Is the modern healthcare system structurally broken?",
  "Should vaccines be mandatory for all citizens?",
  "Is mental health becoming overmedicalized?",
  "Should alcohol be regulated as strictly as tobacco?",
  "Is extended fasting effective or dangerous?",
  "Should organ donation be opt-out by default?",
  "Is self-medication a personal right?",
  "Should therapy be fully state-subsidized?",
  "Is Western medicine too reliant on pharmaceuticals?",
  "Should cosmetic surgery require a mental health evaluation?",
  "Is obesity primarily a disease or a lifestyle choice?",
  "Should energy drinks be banned for under-18s?",
  "Is alternative medicine dangerous when used instead of treatment?",
  "Should assisted dying be available to all terminal patients?",
  "Is the wellness industry mostly a scam?",
  "Should fast food be taxed like cigarettes?",
  "Is addiction a moral failing or a brain disease?",
  "Should hospitals be public or private institutions?",
  "Is intermittent fasting scientifically sound or a fad?",
  "Should psychedelic-assisted therapy be fully legalized?",
  "Is the BMI an outdated and harmful measurement?",
  "Should GLP-1 weight-loss drugs be freely available?",
  "Is social media a public health crisis?",
  "Should pharmaceutical companies be non-profit by law?",
  "Is loneliness the most underrated health epidemic?",
  "Should ultra-processed food be banned from schools?",
  "Is gym culture promoting or harming body image?",
  "Should mental health insurance coverage equal physical?",
  "Is preventive healthcare chronically underfunded?",
  "Should sugar be regulated like alcohol?",
  "Is the opioid crisis a healthcare failure or a legal failure?",
  "Should hospitals be financially penalized for medical errors?",
  "Is telemedicine as effective as in-person consultation?",
  "Is work-life balance an achievable goal or a myth?",
  "Should all healthcare workers be required to be vaccinated?",
  "Is cosmetic surgery normalizing body dysmorphia?",
  "Should sleep be a protected right in employment law?",
  "Is cold-water plunging evidence-based or marketing?",
  "Should patients own their own health data?",
  "Is the anti-vaccine movement a public safety threat?",
  "Should there be a tax on sedentary lifestyles?",
  "Is mental health leave from work being abused?",

  // Environment & Climate
  "Is nuclear energy the only realistic path to net zero?",
  "Should flying be taxed proportionally to carbon emissions?",
  "Is veganism the only genuinely ethical diet?",
  "Should single-use plastic be globally banned immediately?",
  "Is climate change the single greatest threat to humanity?",
  "Should companies be legally required to offset all carbon?",
  "Is rewilding more important than intensive agriculture?",
  "Should all petrol and diesel cars be banned by 2030?",
  "Is ecotourism net positive or net negative?",
  "Should factory farming be made illegal?",
  "Is geoengineering worth the risk?",
  "Should wealthy nations fund climate adaptation in poorer nations?",
  "Is fast fashion an environmental catastrophe?",
  "Should all zoos be closed?",
  "Is organic farming scalable enough to feed the world?",
  "Should space exploration be paused during the climate crisis?",
  "Is individual consumer action meaningful for climate?",
  "Should governments ban meat advertising?",
  "Is the circular economy a real solution?",
  "Should food waste be a criminal offense?",
  "Is solar energy sufficient without nuclear as backup?",
  "Should all airlines pay a mandatory climate surcharge?",
  "Is degrowth the only sustainable economic path?",
  "Should electric vehicles be heavily subsidized?",
  "Is recycling a meaningful solution or a distraction?",
  "Should fossil fuel companies be required to fund renewables?",
  "Is overpopulation still an environmental threat?",
  "Should wealthy individuals have a personal carbon allowance?",
  "Is urban vertical farming the future of food production?",
  "Should commercial fishing be cut in half to save oceans?",
  "Is direct air carbon capture viable and scalable?",
  "Should all new buildings be legally required to be green?",
  "Is environmental activism more effective than policy?",
  "Should deforestation be classified as a war crime?",
  "Is a plant-based diet sufficient to reverse climate damage?",
  "Should governments subsidize lab-grown meat?",
  "Is the ocean already too acidic to recover fully?",
  "Should every person have a legally protected right to clean air?",
  "Is renewable energy reliable enough for full grid supply?",
  "Should actively denying climate science be illegal?",
  "Is nuclear fusion always 20 years away?",
  "Should private jets be banned?",
  "Is the carbon offset market a scam?",

  // Finance & Money
  "Is Bitcoin a better store of value than gold?",
  "Should cryptocurrency be regulated like traditional currency?",
  "Are NFTs permanently dead or still evolving?",
  "Should the global minimum wage be standardized?",
  "Is day trading morally equivalent to gambling?",
  "Should student loans be interest-free by law?",
  "Does rent control help or hurt the housing market?",
  "Should large inheritance be taxed at 100% above a threshold?",
  "Is compound interest an ethical financial mechanism?",
  "Should banks be nationalized?",
  "Is the housing market permanently broken?",
  "Should financial literacy be core curriculum from age 8?",
  "Is passive index investing slowly destroying market efficiency?",
  "Should a global wealth tax be introduced?",
  "Is tipping culture in the US out of control?",
  "Should credit scores be abolished?",
  "Is inflation always economically harmful?",
  "Should payday loan companies be made illegal?",
  "Is the stock market structurally rigged against retail investors?",
  "Should there be a universal global corporate tax floor?",
  "Is the gig economy creating a lost generation of workers?",
  "Should pension contributions be mandatory for all employers?",
  "Is the US dollar's reserve status coming to an end?",
  "Should governments be permitted to run persistent deficits?",
  "Is ESG investing effective or pure greenwashing?",
  "Should hedge funds face much stricter regulation?",
  "Is frugality a moral virtue or economic depressant?",
  "Should physical cash be abolished?",
  "Is personal debt always a personal failure?",
  "Should AI and robots pay a form of income tax?",
  "Is universal basic income fiscally sustainable?",
  "Should any bank be allowed to be too big to fail?",
  "Is inflation a hidden tax on working people?",
  "Should gambling be banned or strictly limited?",
  "Is trickle-down economics real or a myth?",
  "Should executives be paid exclusively in company stock?",
  "Is financial independence the most important life goal?",
  "Should there be a legal maximum profit margin?",
  "Is modern central banking making inequality worse?",
  "Should sovereign wealth funds invest in domestic infrastructure?",
  "Is the venture capital model broken?",
  "Should there be a financial transaction tax?",

  // Media & Entertainment
  "Should social media influencers be regulated like advertisers?",
  "Is reality TV making society coarser?",
  "Should quality journalism always be free to access?",
  "Is streaming killing the theatrical cinema experience?",
  "Should violent video games be banned for under-16s?",
  "Is podcast culture replacing traditional journalism?",
  "Should celebrities stay out of politics entirely?",
  "Is the music industry still exploiting artists?",
  "Should national newspapers receive government subsidies?",
  "Is binge-watching multiple episodes a harmful habit?",
  "Should professional athletes be required to be role models?",
  "Is Hollywood too risk-averse and sequel-dependent?",
  "Should all advertising to children under 12 be banned?",
  "Is political satire a form of journalism?",
  "Should paparazzi photography be illegal without consent?",
  "Is true crime content exploiting victims for entertainment?",
  "Should streaming platforms share a bigger cut with creators?",
  "Is the gaming industry promoting toxic masculinity?",
  "Should all social media accounts be verified with real identity?",
  "Is TikTok a legitimate national security threat?",
  "Should copyright terms be reduced to 20 years?",
  "Is fan fiction a form of copyright theft?",
  "Should news anchors be banned from sharing personal opinions?",
  "Is the Marvel formula killing creative cinema?",
  "Should stand-up comedians have unlimited artistic freedom?",
  "Is reality dating television damaging relationship expectations?",
  "Should AI be allowed to write commercial screenplays?",
  "Is traditional radio a dead medium?",
  "Should video games be classified as a protected art form?",
  "Is the 24-hour news cycle harmful to public discourse?",
  "Should social media platforms be editorially liable for content?",
  "Is music streaming paying artists fairly?",
  "Should advertising be banned from children's programming entirely?",
  "Is nostalgia-driven entertainment a creative failure?",

  // Ethics & Philosophy
  "Is lying ever morally justified?",
  "Should animals have the same legal rights as humans?",
  "Is capital punishment ever morally defensible?",
  "Should privacy be treated as an absolute right?",
  "Is there such a thing as a truly victimless crime?",
  "Should moral relativism be accepted or rejected?",
  "Is civil disobedience a moral duty in unjust systems?",
  "Should whistleblowers always receive full legal protection?",
  "Is eating meat morally defensible in 2025?",
  "Should we prioritize living people over future generations?",
  "Is colonialism still materially shaping outcomes today?",
  "Should forgiveness be unconditional?",
  "Is human cloning ever ethically justifiable?",
  "Should altruism be the highest moral standard?",
  "Is it ethical to have children in the current climate?",
  "Is justice possible without some form of punishment?",
  "Should morality be based on outcomes or rules?",
  "Is cultural appropriation always harmful?",
  "Should we prioritize helping those near us before strangers?",
  "Is radical transparency always ethical?",
  "Should art be held to moral standards?",
  "Should organ donation be a legal obligation after death?",
  "Is it ethical to keep animals as pets?",
  "Should we prioritize longevity or quality of life?",
  "Is charitable giving a moral obligation for the wealthy?",
  "Should corporations be legally required to have ethical duties beyond profit?",
  "Is moral progress real or an illusion?",
  "Is consumerism inherently unethical?",
  "Should we always be honest even when truth causes harm?",
  "Is it ethical to have a child you cannot financially support?",
  "Should individual rights be sacrificed for collective good?",
  "Is personal revenge ever morally justified?",
  "Should future generations have legal rights enforceable today?",
  "Is factory-farmed food consumption ethically defensible?",
  "Should we be morally judged for our ancestors' actions?",
  "Is non-violence always the highest moral choice?",
  "Should we eat lab-grown meat?",
  "Is it unethical to be extremely wealthy?",
  "Should euthanasia for non-terminal suffering be legal?",
  "Is it wrong to bring children into a suffering world?",
  "Should there be a universal moral code across cultures?",

  // Sports
  "Should athletes be allowed to use performance-enhancing drugs?",
  "Is esports a legitimate sport?",
  "Should sports clubs be publicly owned by fans?",
  "Is paying athletes more than teachers ethical?",
  "Should women and men compete in the same events?",
  "Is tackle football too dangerous for children?",
  "Should the Olympics be abolished?",
  "Is cheating in sport ever morally acceptable?",
  "Should professional athletes be required to be political?",
  "Is horse racing an ethical sport?",
  "Should boxing be banned for health reasons?",
  "Are sports agents over-compensated?",
  "Should every sport have a strict salary cap?",
  "Is golf too elitist for public funding?",
  "Should all school sport be co-ed?",
  "Is sports gambling ruining fan engagement?",
  "Should athletes be tested for drugs year-round?",
  "Is the football World Cup format broken?",
  "Should AI referees replace human officials?",
  "Is competitive cheerleading a legitimate sport?",
  "Should college athletes be paid professional wages?",
  "Is the Premier League too dominated by sovereign wealth?",
  "Should there be strict age limits on youth competition?",
  "Is Formula 1 relevant to anyone outside Europe?",
  "Should national anthems be removed from sporting events?",
  "Is cricket too slow for modern global audiences?",
  "Should athletes be forced to retire earlier to protect health?",
  "Is sports tribalism a form of harmful tribalism?",
  "Should the Tour de France be restructured or discontinued?",
  "Is esports more meritocratic than traditional sports?",
  "Should sports governing bodies be democratically elected?",
  "Is doping in sport a victimless act?",

  // Science & The Future
  "Should humans attempt to colonize Mars?",
  "Is extending human lifespan beyond 150 ethical?",
  "Should gene editing of human embryos be permitted?",
  "Is cryogenic freezing a viable future technology?",
  "Should nuclear power be the backbone of a green grid?",
  "Is space tourism ethical during an active climate crisis?",
  "Should we actively search for and contact alien civilizations?",
  "Is CRISPR technology more dangerous than beneficial?",
  "Should aging be reclassified and treated as a disease?",
  "Is artificial general intelligence inevitable this century?",
  "Should terraforming other planets be pursued?",
  "Is the multiverse a scientific theory or philosophy?",
  "Should we attempt to resurrect extinct species?",
  "Is nuclear fusion always 30 years away?",
  "Should human cognitive augmentation be permitted?",
  "Is human population decline a global crisis?",
  "Should scientific research be subject to ethics limits?",
  "Is brain uploading a desirable or dystopian future?",
  "Should asteroid mining be internationally regulated?",
  "Is infinite economic growth mathematically possible?",
  "Should space be governed by international treaty?",
  "Is overpopulation still the defining environmental threat?",
  "Should we seed life on other planets?",
  "Is climate engineering worth the risk of unintended consequences?",
  "Should the internet be governed by a global authority?",
  "Is radical life extension fair to future generations?",
  "Should nanotechnology be tightly regulated from the outset?",
  "Is digital immortality achievable or desirable?",
  "Should private companies be permitted to own space territory?",
  "Is superintelligence the last invention humanity will make?",
  "Should we pursue a post-scarcity economy?",
  "Is human space exploration worth the cost?",

  // Crypto & Web3
  "Is Bitcoin a legitimate currency or speculative asset?",
  "Should stablecoins be regulated like bank deposits?",
  "Is decentralized finance safer than traditional banking?",
  "Should governments issue their own digital currencies?",
  "Is crypto mining too damaging to the environment?",
  "Should NFTs ever have had real monetary value?",
  "Is Web3 a genuine paradigm shift or hype?",
  "Should crypto exchanges be regulated like stock markets?",
  "Is Ethereum more useful than Bitcoin?",
  "Should crypto be legal tender anywhere?",
  "Is the DAO model a viable governance structure?",
  "Should smart contracts be legally binding?",
  "Is crypto enabling money laundering at scale?",
  "Should crypto be banned in authoritarian regimes to protect dissidents?",
  "Is the metaverse a failure of imagination?",
  "Should digital assets be included in inheritance law?",
  "Is blockchain useful outside of cryptocurrency?",
  "Should there be a global crypto tax framework?",
  "Is DeFi democratizing finance or creating new risks?",
  "Should crypto wallets require identity verification?",

  // Relationships & Society
  "Is monogamy a natural human state?",
  "Should marriage as an institution be abolished?",
  "Is divorce too easy or too hard to obtain?",
  "Should prenuptial agreements be mandatory?",
  "Is long-distance relationship a real relationship?",
  "Should the legal age of marriage be 21?",
  "Is social media harming long-term relationships?",
  "Should co-habitation before marriage be encouraged?",
  "Is friendship more important than romance?",
  "Should adultery be illegal?",
  "Is online dating superior to meeting in person?",
  "Should relationship counselling be required before divorce?",
  "Is jealousy ever healthy in a relationship?",
  "Should gender roles in relationships be entirely rejected?",
  "Is having children the default or a deliberate choice?",
  "Should the state have any interest in who people marry?",
  "Is romantic love a cultural construct?",
  "Should couples share all finances?",
  "Is it possible to remain close friends with an ex?",
  "Should social media be off-limits in relationships?",
  "Is soulmate theory harmful to relationships?",
  "Should couples need a license to have children?",
  "Is age gap relationships inherently problematic?",
  "Should open relationships be socially normalized?",
  "Is ghosting ever an acceptable way to end things?",

  // Food & Diet
  "Should restaurants be legally required to show calorie counts?",
  "Is veganism ethical or just another form of elitism?",
  "Should alcohol be banned at all sporting events?",
  "Is food fusion disrespectful to source cultures?",
  "Should shark fin soup be globally banned?",
  "Is street food safer than sit-down restaurants?",
  "Should fast food chains be removed from schools?",
  "Is coffee net harmful to human health?",
  "Should energy drinks be banned entirely for minors?",
  "Is breakfast the most important meal of the day?",
  "Should governments subsidize fruits and vegetables?",
  "Is food delivery culture killing independent restaurants?",
  "Should there be a fat tax on unhealthy products?",
  "Should cultural dishes be legally protected?",
  "Is diet culture inherently harmful to mental health?",
  "Should alcohol be restricted to licensed venues only?",
  "Is going vegan genuinely effective for personal climate impact?",
  "Should there be a monthly meat allowance per person?",
  "Should commercial food waste be criminalized?",
  "Should cooking be a mandatory school subject?",
  "Is organic food worth the premium it commands?",
  "Should food be labeled with its full carbon footprint?",
  "Is food tourism a form of cultural exploitation?",
  "Should humans adopt insect protein to save the planet?",
  "Is the celebrity chef industry creating unrealistic food expectations?",
  "Should plant-based food replace meat in public institutions?",
  "Is the wine industry too pretentious for its own good?",
  "Should food banks be replaced by universal food vouchers?",
  "Is mainstream nutrition science too contradictory to follow?",
  "Should ultra-processed food carry warning labels like cigarettes?",
  "Is it ethical to eat food produced by underpaid workers?",
  "Should school lunches be free and nutritious for all?",
  "Is the restaurant industry too reliant on tips as compensation?",

  // Urban Life & Housing
  "Should cities ban private cars from their centres?",
  "Is gentrification ever beneficial to a community?",
  "Should short-term rentals like Airbnb be banned in cities?",
  "Is public transport always better than private car ownership?",
  "Should housing be treated as a human right?",
  "Is urban sprawl destroying the quality of city life?",
  "Should there be rent caps in all major cities?",
  "Is the suburbs a failed model of urban planning?",
  "Should cycling infrastructure replace car lanes?",
  "Is social housing the only solution to the housing crisis?",
  "Should all city parks be free from commercial activity?",
  "Is noise pollution as serious as air pollution?",
  "Should cities ban advertising in public spaces?",
  "Is street homelessness a housing failure or personal failure?",
  "Should urban areas have night-time economies regulated?",
  "Is the 15-minute city model achievable?",
  "Should empty commercial properties be requisitioned?",
  "Is mixed-income housing policy effective?",
  "Should property ownership be capped per person?",
  "Is high-density living better for the environment?",
  "Should jaywalking ever be illegal?",
  "Is graffiti public art or public nuisance?",
  "Should cities be designed around children, not cars?",
  "Is remote work reducing the purpose of cities?",
  "Should public toilets be free and abundant?",

  // Travel & Global
  "Is mass tourism destroying the destinations it serves?",
  "Should frequent flyers pay a progressive air travel tax?",
  "Is cultural tourism ever truly respectful?",
  "Should travel to authoritarian regimes be discouraged?",
  "Is the backpacker model of travel environmentally irresponsible?",
  "Should cruise ships be banned from sensitive marine areas?",
  "Is visa-free travel a human right?",
  "Should travel rewards points systems be abolished?",
  "Is voluntourism more harm than help?",
  "Should governments subsidize domestic tourism?",
  "Is Instagram ruining travel destinations?",
  "Should there be a global tourist cap on popular sites?",
  "Is the passport system an outdated form of control?",
  "Should business class seating be abolished on flights?",
  "Is digital nomad culture sustainable long-term?",
  "Should heritage sites charge higher prices to tourists?",
  "Is solo travel always safe for women?",
  "Should travel companies be required to carbon offset every trip?",
  "Is the travel industry recovering the right way post-COVID?",
  "Should there be a global tourist tax to fund conservation?",

  // Gender & Identity
  "Should gender be removed from all official documents?",
  "Is the gender pay gap primarily caused by discrimination?",
  "Should trans athletes compete in their identified gender category?",
  "Is gender a spectrum or a binary?",
  "Should parental leave be equal and mandatory for all parents?",
  "Is feminism still necessary in Western countries?",
  "Should gender-neutral language be used in all legislation?",
  "Is toxic masculinity a useful concept or divisive?",
  "Should single-sex spaces remain legally protected?",
  "Is positive discrimination for women in leadership effective?",
  "Should hormone therapy for minors be available without parental consent?",
  "Is the wage gap in 2025 still primarily a gender issue?",
  "Should all-male boards be made illegal?",
  "Is the concept of gender non-binary scientifically sound?",
  "Should beauty standards be regulated in advertising?",
  "Is unconscious gender bias the primary barrier for women in STEM?",
  "Should domestic labour be given an economic value in GDP?",
  "Is the term 'woman' biologically or socially defined?",
  "Should male-dominated industries have enforced gender quotas?",
  "Is gender identity therapy effective?",

  // Race & Diversity
  "Should race be a factor in university admissions?",
  "Is diversity hiring a form of discrimination?",
  "Should statues of historical slave owners be removed?",
  "Is systemic racism a real and measurable phenomenon?",
  "Should reparations be paid to descendants of enslaved people?",
  "Is colourblindness a useful or harmful approach to race?",
  "Should race be included as a question on census forms?",
  "Is implicit bias training effective?",
  "Should all history curricula include colonialism?",
  "Is white privilege a useful analytical concept?",
  "Should hate speech laws be expanded?",
  "Is representation in media sufficient to drive real change?",
  "Should companies publicly report their racial pay gaps?",
  "Is multiculturalism strengthening or fragmenting societies?",
  "Should race-based scholarships exist?",
  "Is cultural assimilation a form of cultural erasure?",
  "Should police forces reflect the racial makeup of communities they serve?",
  "Is racial profiling ever justified in law enforcement?",
  "Should schools teach the full history of empire?",
  "Is the word 'woke' now meaningless?",

  // Mental Health & Psychology
  "Should therapy be available free to everyone?",
  "Is social media the primary driver of teen depression?",
  "Should employers be required to accommodate mental illness?",
  "Is the diagnosis of ADHD being over-applied?",
  "Should antidepressants be harder to prescribe?",
  "Is toxic positivity harmful?",
  "Should smartphones carry mental health warnings?",
  "Is loneliness a public health emergency?",
  "Should mindfulness and meditation be evidence-based?",
  "Is self-diagnosis via the internet harmful?",
  "Should burnout be a recognized medical condition?",
  "Is online therapy as effective as face-to-face?",
  "Should psychological safety be legally required at work?",
  "Is the mental health industry over-pathologizing normal sadness?",
  "Should schools have dedicated mental health staff?",
  "Is the stigma around mental health finally reducing?",
  "Should mental health days be a legal right at work?",
  "Is grief being medicalized too quickly?",
  "Should psychedelic drugs be reclassified for therapy?",
  "Is trauma theory being misapplied in mainstream culture?",

  // Law & Justice
  "Should all drugs be fully legalized and regulated?",
  "Is the jury system still fit for purpose?",
  "Should prisons be abolished?",
  "Is restorative justice more effective than punitive justice?",
  "Should lawyers be required to take pro bono cases?",
  "Is the legal system too expensive for ordinary citizens?",
  "Should solitary confinement be banned as torture?",
  "Is a life sentence ever proportionate?",
  "Should the age of criminal responsibility be raised to 18?",
  "Is plea bargaining corrupting the justice system?",
  "Should hate crime sentencing be tougher?",
  "Is the war on drugs a policy failure?",
  "Should non-violent offenders go to prison at all?",
  "Is rehabilitation more effective than incarceration?",
  "Should legal aid be universally funded?",
  "Is police abolition a viable policy?",
  "Should body cameras be mandatory for all police officers?",
  "Is stop and search policing ever justified?",
  "Should the statute of limitations be abolished for serious crimes?",
  "Is anonymous jury selection fair?",
  "Should judges be elected or appointed?",
  "Is the right to silence ever harmful to justice?",
  "Should repeat offenders receive automatically longer sentences?",
  "Is criminal record expungement too difficult to access?",
  "Should private prisons be abolished entirely?",
];

export function pickRandom(n = 4): string[] {
  const pool = [...QUESTION_BANK];
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, n);
}
